#ifndef BALTAMATICA_MCP_PROTOCOL_H
#define BALTAMATICA_MCP_PROTOCOL_H

#define BALTAMATICA_MCP_DEFAULT_HOST "127.0.0.1"
#define BALTAMATICA_MCP_DEFAULT_PORT 31415
#define BALTAMATICA_MCP_BACKLOG 4
#define BALTAMATICA_MCP_MAX_LINE (16 * 1024 * 1024)
#define BALTAMATICA_MCP_MAX_ID 128
#define BALTAMATICA_MCP_MAX_METHOD 64
#define BALTAMATICA_MCP_MAX_CODE 60000
#define BALTAMATICA_MCP_MAX_PATH 4096
#define BALTAMATICA_MCP_MAX_ERROR 512

#define BALTAMATICA_MCP_METHOD_EXECUTE_CODE "execute_code"
#define BALTAMATICA_MCP_METHOD_RUN_SCRIPT "run_script"
#define BALTAMATICA_MCP_METHOD_CLEAR_WORKSPACE "clear_workspace"
#define BALTAMATICA_MCP_METHOD_STATUS "status"
#define BALTAMATICA_MCP_METHOD_LIST_VARIABLES "list_variables"
#define BALTAMATICA_MCP_METHOD_GET_VARIABLE "get_variable"
#define BALTAMATICA_MCP_METHOD_SET_VARIABLE "set_variable"
#define BALTAMATICA_MCP_METHOD_SHUTDOWN "shutdown"

#define BALTAMATICA_MCP_ERROR_BAD_REQUEST "BAD_REQUEST"
#define BALTAMATICA_MCP_ERROR_EVAL "EVAL_ERROR"
#define BALTAMATICA_MCP_ERROR_SCRIPT "SCRIPT_ERROR"
#define BALTAMATICA_MCP_ERROR_VARIABLE "VARIABLE_ERROR"
#define BALTAMATICA_MCP_ERROR_INTERNAL "INTERNAL_ERROR"

#endif
